#!/usr/bin/python3
# SPDX-FileCopyrightText: 2022 Shoya Mitomi
# SPDX-License-Identifier: BSD-3-Clause

import sys

ans = 0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)
print(ans)
if ans%2==0:
    print(str(ans) + " Even numberes")
else:
    print(str(ans) + " Odd numberes")


